puts "normal \e[106m red \e[0m normal again"
puts "normal \e[41m colored text \e[0m normal again"
puts "normal \e[46m colored text \e[0m normal again"
puts "normal \e[100m colored text \e[0m normal again"
puts "normal \e[40m colored text \e[0m normal again"